### PR TITLE
apply upstream patches

### PR DESCRIPTION
**Pull request by samansmink**
applies the combined patch from duckdb/duckdb

### CODE REVIEW

**Comment by Mytherin** [comment]
Looks like this patch is missing:

```diff
diff --git a/test/all_pg_types.sql b/test/all_pg_types.sql
index d2312bc..5b61607 100644
--- a/test/all_pg_types.sql
+++ b/test/all_pg_types.sql
@@ -185,3 +185,9 @@ INSERT INTO mixed_arrays VALUES (
 INSERT INTO mixed_arrays VALUES (
 	ARRAY[1, 2, 3]
 );
+
+CREATE TYPE composite_a AS (i INTEGER, j INTEGER);
+CREATE TYPE composite_b AS (a composite_a, k INTEGER);
+CREATE TABLE composites_of_composites (b composite_b);
+
+INSERT INTO composites_of_composites VALUES (((1,2),3)), (((4,5),6)), (((7,8),9));
\ No newline at end of file

```

**Comment by Mytherin** [comment]
`EXCLUDE (UHUGEINT)` for test_all_types()

**Comment by Mytherin** [comment]
Missing `----` at statement error

**Comment by samansmink** [comment]
@Mytherin got em!

**Comment by Mytherin** [comment]
Thanks!

**Pull request merged**
